version: '3.1'

services:

  frontend_container:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile 
