name: Fortune cookie
on: 
  push:
    branches:
      - "feature/**"
  
env:
  docker_username: ${{ secrets.USERNAME }}
  docker_password: ${{ secrets.PASSWORD }}
  git_commit: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: [self-hosted, dev]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: |
            .
            !.git
      - name: Upload kubernetes deployment yaml
        uses: actions/upload-artifact@v3
        with:
          name: kube-dep
          path: kubernetes-deployment.yaml
      - name: Upload test script
        uses: actions/upload-artifact@v3
        with:
          name: test-script
          path: curl-test.sh

  Performance-test: 
    runs-on: [self-hosted, dev]
    needs: [Clone-down]
    steps: 
    - name: Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.16.1"
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: code
        path: .
    - name: build and test
      run: cd frontend && go build && go test

  push-docker-images:
    runs-on: [self-hosted, dev]
    needs: [Clone-down, Performance-test]
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v3
      with: 
          name: code
          path: .
    - name: build docker
      run: chmod +x ci/build-docker-dev.sh && ci/build-docker-dev.sh
    - name: push docker
      run: chmod +x ci/push-docker-dev.sh && ci/push-docker-dev.sh

  Curl-tests:
    runs-on: [self-hosted, dev]
    needs: [push-docker-images]
    steps:
      - name: Start redis
        run: docker run -p 6379:6379 -d redis
      - name: Start backend
        run: docker run -d rasmj/backend:latest-dev
      - name: Start frontend
        run: docker run -p 8080:8080 -d rasmj/frontend:latest-dev
      - name: Download test-script
        uses: actions/download-artifact@v3
        with:
          name: test-script
          path: .
      - name: Run test script
        run: chmod +x curl-test.sh && ./curl-test.sh


  Deploy-to-Kubernetes:
    runs-on: [self-hosted, stag]
    needs: [Performance-test, push-docker-images]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: kube-dep
          path: .
      - name: Apply with kubectl
        run: kubectl apply -f kubernetes-dev-deployment.yaml
  