name: Fortune cookie
on: 
  push:
    branches:
      - main
  
env:
  docker_username: ${{ secrets.USERNAME }}
  docker_password: ${{ secrets.PASSWORD }}
  git_commit: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: [self-hosted, prod]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: |
            .
            !.git
      - name: Upload kubernetes deployment yaml
        uses: actions/upload-artifact@v3
        with:
          name: kube-dep
          path: kubernetes-deployment.yaml
      - name: Upload test script
        uses: actions/upload-artifact@v3
        with:
          name: test-script
          path: |
            curl-test.sh
            docker-compose.yaml

  push-docker-images:
    runs-on: [self-hosted, prod]
    needs: [Clone-down]
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v3
      with: 
          name: code
          path: .
    - name: build docker
      run: chmod +x ci/build-docker.sh && ci/build-docker.sh
    - name: push docker
      run: chmod +x ci/push-docker.sh && ci/push-docker.sh

  Performance-test: 
    runs-on: [self-hosted, prod]
    needs: [Clone-down]
    steps: 
    - name: Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.16.1"
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: build and test
      run: cd frontend && go build && go test  

  Curl-tests:
    runs-on: [self-hosted, prod]
    needs: [push-docker-images]
    steps:
      - name: Download test-script
        uses: actions/download-artifact@v3
        with:
          name: test-script
          path: .
      - name: Start docker compose
        run: docker-compose up
      - name: Run test script
        run: chmod +x curl-test.sh && ./curl-test.sh
      - name: Stop docker containers
        run: docker-compose down

  Deploy-to-Kubernetes:
    runs-on: [self-hosted, stag]
    needs: [Performance-test, push-docker-images]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: kube-dep
          path: .
      - name: Apply with kubectl
        run: kubectl apply -f kubernetes-deployment.yaml
  