name: Fortune cookie
on: 
  pull_request:
    branches:
      - main
  
env:
  docker_username: ${{ secrets.USERNAME }}
  docker_password: ${{ secrets.PASSWORD }}
  git_commit: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: [self-hosted, stag]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: |
            .
            !.git
      - name: Upload kubernetes deployment yaml
        uses: actions/upload-artifact@v3
        with:
          name: kube-dep
          path: kubernetes-deployment.yaml

  Performance-test: 
    runs-on: [self-hosted, stag]
    needs: [Clone-down]
    steps: 
    - name: Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.16.1"
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: code
        path: .
    - name: build and test
      run: cd frontend && go build && go test 

  push-docker-images:
    runs-on: [self-hosted, stag]
    needs: [Clone-down, Performance-test]
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v3
      with: 
          name: code
          path: .
    - name: build docker
      run: chmod +x ci/build-docker-stag.sh && ci/build-docker-stag.sh
    - name: push docker
      run: chmod +x ci/push-docker-stag.sh && ci/push-docker-stag.sh


  Curl-tests:
    runs-on: [self-hosted, dev]
    needs: [push-docker-images]
    steps:
      - name: Start redis
        run: docker run -p 6379:6379 -d redis
      - name: Start backend
        run: docker run -d rasmj/backend:latest-stag
      - name: Start frontend
        run: docker run -p 8080:8080 -d rasmj/frontend:latest-stag
      - name: Download test-script
        uses: actions/download-artifact@v3
        with:
          name: test-script
          path: .
      - name: Run test script
        run: chmod +x curl-test.sh && ./curl-test.sh

  Deploy-to-Kubernetes:
    runs-on: [self-hosted, stag]
    needs: [Performance-test, push-docker-images]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: kube-dep
          path: .
      - name: Apply with kubectl
        run: kubectl apply -f kubernetes-stag-deployment.yaml
  