name: Fortune cookie
on: 
  pull_request:
    branches:
      - main
  
env:
  docker_username: ${{ secrets.USERNAME }}
  docker_password: ${{ secrets.PASSWORD }}
  git_commit: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: [self-hosted, stag]
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: |
            .
            !.git

  Performance-test: 
    runs-on: [self-hosted, stag]
    needs: [Clone-down]
    steps: 
    - name: Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.16.1"
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: code
        path: .
    - name: build and test
      run: cd frontend && go build && go test             
  